DROP TABLE IF EXISTS author CASCADE;
CREATE TABLE IF NOT EXISTS author (
  id SERIAL PRIMARY KEY,
  author_name VARCHAR(32)
);

DROP TABLE IF EXISTS genre CASCADE;
CREATE TABLE IF NOT EXISTS genre (
  id SERIAL PRIMARY KEY,
  book_genre VARCHAR(32)
);

DROP TABLE IF EXISTS book;
CREATE TABLE IF NOT EXISTS book (
 id SERIAL PRIMARY KEY,
 title VARCHAR(32),
 description TEXT,
 img_url  VARCHAR(512),
 author_id INTEGER REFERENCES author(id),
 genre_id INTEGER REFERENCES genre(id)
);
